Dev-Production Rotation

diff --git a/serfs/inkget b/serfs/inkget
--- a/serfs/inkget
+++ b/serfs/inkget
@@ -16,7 +16,7 @@
 APPNAME=$1
 
 # Include the config files
-. /var/local/verb/configs/siteinkget
+. /opt/verb/conf/siteinkget
 
 if [ "${INKGET_REPO}" = "NOT_SET" ]; then
 echo "inkNet is not setup, so no repo is available. Can't download the necessary package."
@@ -25,11 +25,15 @@ fi
 
 # zjz
 if [ $INKGET_METHOD = "ZJZ" ]; then
-/var/local/verb/donjon/repoupdate/${APPNAME}.updaterepo; wait
-cp /var/local/verb/repo/${APPNAME}.vtxz .
+/opt/verb/donjon/repoupdate/${APPNAME}.updaterepo; wait
+## Check repo for failed DL
+ if [ "$2" = "check" ] && [ -f "/opt/verb/donjon/repoupdate/${APPNAME}.failed" ]; then
+ exit 4; fi
+## Continue
+cp /opt/verb/repo/${APPNAME}.vtxz .
 echo "Copied for install."
  if [ $INKGET_REPO = "TEMP" ]; then
-rm /var/local/verb/repo/${APPNAME}.vtxz
+rm /opt/verb/repo/${APPNAME}.vtxz
 echo "Temp repo files cleaned-up."
  else
 echo "Repo files kept."
@@ -43,7 +47,7 @@ fi
 
 # inker
 if [ $INKGET_METHOD = "INKER_CP" ]; then
-cp /var/local/ink/repo/${APPNAME}.vtxz .
+cp /opt/ink/repo/${APPNAME}.vtxz .
 fi
 
 ## DEV NOTE: Other secure methods are planned in the roadmap
diff --git a/serfs/installfossil b/serfs/installfossil
--- a/serfs/installfossil
+++ b/serfs/installfossil
@@ -11,26 +11,45 @@
 ## ./installfossil adam adam@verb.ink Adamp4$$w0RD
 
 
+CVAPPNAME=fossil
+
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
 
 NEWUSER=$1
 NEWEMAIL=$2
 NEWPASS=$3
 
+
+cd /var/www/vapps
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+rm -f ${CVAPPNAME}
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+
+rm -f /usr/bin/fossil
+mv /var/www/vapps/fossil /usr/bin
+fossil all rebuild
+
 # Install and set up directories
-apt install -y fossil
-mkdir /var/www/vip/fossil
-rm -rf /var/www/html/vip.fossil
-ln -s /var/www/vip/fossil /var/www/html/vip.fossil
-chown -R www-data:www-data  /var/www/html
+mkdir -p /var/www/vip/fossil
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}
+chown -R www-data:www-data  /var/www/html/vip.fossil
 chown -R www-data:www-data /var/www/vip
 
 # Create the first default fossil
 cd /var/www/vip/fossil
-fossil new index.fossil
-chown www-data:www-data index.fossil
+fossil new index.fossil; wait
+chown www-data:www-data index.fossil; wait
 echo "#!/usr/bin/fossil
 repository: /fossil/index.fossil
 
@@ -47,7 +66,7 @@ repository: /fossil/dinosaur.fossil" > dinosaur.cgi
 chmod 750 dinosaur.cgi
 
 # Final chown to allow database to be writable
-chown -R www-data:www-data /var/www/vip/fossil
+chown -R www-data:www-data /var/www/vip/fossil; wait
 
 # Add the user
 fossil user new ${NEWUSER} ${NEWEMAIL} ${NEWPASS} --repository index.fossil
diff --git a/serfs/installnet2ftp b/serfs/installnet2ftp
--- a/serfs/installnet2ftp
+++ b/serfs/installnet2ftp
@@ -12,17 +12,25 @@
 CVAPPNAME=net2ftp
 
 # Include the configs
-. /var/local/verb/configs/sitenameip
-. /var/local/verb/configs/siteurilist
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
 
 # Download and unpack
 cd /var/www/vapps
-/var/local/verb/serfs/inkget ${CVAPPNAME}; wait
-/var/local/verb/serfs/vtxzout ${CVAPPNAME}; wait
-rm -rf /var/www/html/vip.net2ftp
-ln -s /var/www/vapps/net2ftp /var/www/html/vip.net2ftp
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}
-chown -R www-data:www-data /var/www/html/vip.net2ftp
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+echo "Failed to retrieve from the repo."
+exit 4; fi
+
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+/opt/verb/serfs/setvapplinkon ${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}; wait
+chown -R www-data:www-data /var/www/html/vip.net2ftp; wait
 
 # Settings
 cd net2ftp
diff --git a/serfs/installoctober b/serfs/installoctober
--- a/serfs/installoctober
+++ b/serfs/installoctober
@@ -25,7 +25,7 @@ CLEANNAME=$(echo $DOMAIN | sed -e 's/\.//g')
 
 # Check if already installed
 ## Config
-if [ -f /var/local/verb/configs/vapp.${CVAPPNAME}.${DOMAIN} ]; then
+if [ -f /opt/verb/conf/vapp.${CVAPPNAME}.${DOMAIN} ]; then
 echo "This is already installed."
 exit 0; fi
 ## Directory
@@ -39,6 +39,16 @@ if [ -z ${1} ]; then
 echo "You must designate a domain."
 exit 8; fi
 
+# Include the config file
+. /opt/verb/conf/sitenameip
+
+# Download and establish October in the server to pre-created domain
+cd /var/www/vapps
+git clone https://github.com/octobercms/install
+if [ ! -d install ]; then
+echo "Can't download OctoberCMS. I quit."
+exit 4; fi
+
 # Auto database
 if [ -z ${4} ]; then
 DBPASSWORD=$(pwgen -s -1 10); fi
@@ -47,15 +57,6 @@ DBASE=oct$(echo $CLEANNAME | cut -c1-23)$(pwgen -s -1 6); fi
 if [ -z ${3} ]; then
 DBUSER=${DBASE}; fi
 
-# Include the config file
-. /var/local/verb/configs/sitenameip
-
-# Download and establish October in the server to pre-created domain
-cd /var/www/vapps
-git clone https://github.com/octobercms/install
-if [ ! -d install ]; then
-echo "Can't download OctoberCMS. I quit."
-exit 4; fi
 mv install ${CVAPPNAME}.${DOMAIN}
 
 ## Install main themes and plugins
@@ -136,14 +137,14 @@ wget https://github.com/jacoweb/AgencyTheme/archive/master.zip
 unzip master.zip
 rm -f master.zip
 ## Setup links
-rm -f /var/www/html/${DOMAIN}
-ln -s /var/www/vapps/${CVAPPNAME}.${DOMAIN} /var/www/html/${DOMAIN}
-ln -s /var/www/vapps/${CVAPPNAME}.${DOMAIN} /srv/vip/_webapps/
-chown -R www-data:www-data /var/www/html/${DOMAIN}
-chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}.${DOMAIN}
+rm -f /var/www/html/${DOMAIN}; wait
+ln -s /var/www/vapps/${CVAPPNAME}.${DOMAIN} /var/www/html/${DOMAIN}; wait
+ln -s /var/www/vapps/${CVAPPNAME}.${DOMAIN} /srv/vip/_webapps/; wait
+chown -R www-data:www-data /var/www/html/${DOMAIN}; wait
+chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}.${DOMAIN}; wait
 
 # Create the database and credentials
-mysql --defaults-extra-file=/var/local/verb/configs/mysqlboss.cnf -e "
+mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
 CREATE DATABASE  ${DBASE};
 GRANT ALL PRIVILEGES ON ${DBASE}.* TO '${DBUSER}'@'localhost' IDENTIFIED BY '${DBPASSWORD}';
 FLUSH PRIVILEGES;"
@@ -154,7 +155,7 @@ FLUSH PRIVILEGES;"
 echo "#!/bin/sh
 APPDBASE=${DBASE}
 APPDDBUSR=${DBUSER}
-APPDDBPAS=${DBPASSWORD}" > /var/local/verb/configs/vapp.${CVAPPNAME}.${DOMAIN}
+APPDDBPAS=${DBPASSWORD}" > /opt/verb/conf/vapp.${CVAPPNAME}.${DOMAIN}
 
 # Reset all permissions
 chown -R www-data:www-data /var/www/vapps/${CVAPPNAME}.${DOMAIN}
